### ISSUE TITLE
exporter not working with qBittorrent v4.6.0

### ISSUE THREAD

**Issue by robergej** [caseyscarborough/qbittorrent-exporter#18]
Recently upgraded to qBittorrent v4.6.0. (I use [trigus42](https://hub.docker.com/r/trigus42/qbittorrentvpn)'s image. After upgrade, qbittorrent exporter doesn't work anymore. See related log entries:

14:42:38.225 [INFO] qbittorrent.exporter.handler.QbtHttpHandler - Beginning prometheus metrics collection...
14:42:38.230 [INFO] qbittorrent.api.ApiClient - Authorization cookie has not been set, we need to login first.
14:42:38.231 [INFO] qbittorrent.api.ApiClient - Logging in user qbitpi using http://192.168.86.196:8080/api/v2/auth/login
14:42:39.652 [INFO] qbittorrent.api.ApiClient - Response from /app/version endpoint was 200.
14:42:39.652 [INFO] qbittorrent.api.ApiClient - Successfully logged in with qBittorrent version v4.6.0.
14:42:44.449 [INFO] qbittorrent.api.ApiClient - Response from /torrents/info endpoint was 200.
14:42:44.739 [INFO] qbittorrent.api.ApiClient - Response from /app/preferences endpoint was 200.
14:42:44.774 [ERROR] qbittorrent.exporter.handler.QbtHttpHandler - An error occurred calling API
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "None"
	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:320) ~[gson-2.9.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:310) ~[gson-2.9.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:130) ~[gson-2.9.0.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:221) ~[gson-2.9.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:991) ~[gson-2.9.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:956) ~[gson-2.9.0.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:905) ~[gson-2.9.0.jar:?]
	at qbittorrent.api.ApiClient.getRequest(ApiClient.java:161) ~[qbittorrent-exporter.jar:?]
	at qbittorrent.api.ApiClient.getPreferences(ApiClient.java:103) ~[qbittorrent-exporter.jar:?]
	at qbittorrent.exporter.handler.QbtHttpHandler.handleRequest(QbtHttpHandler.java:41) ~[qbittorrent-exporter.jar:?]
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104) ~[undertow-core-2.2.16.Final.jar:2.2.16.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) ~[undertow-core-2.2.16.Final.jar:2.2.16.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256) ~[undertow-core-2.2.16.Final.jar:2.2.16.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136) ~[undertow-core-2.2.16.Final.jar:2.2.16.Final]
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162) ~[undertow-core-2.2.16.Final.jar:2.2.16.Final]
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100) ~[undertow-core-2.2.16.Final.jar:2.2.16.Final]
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57) ~[undertow-core-2.2.16.Final.jar:2.2.16.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.8.6.Final.jar:3.8.6.Final]
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291) ~[xnio-api-3.8.6.Final.jar:3.8.6.Final]
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286) ~[xnio-api-3.8.6.Final.jar:3.8.6.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.8.6.Final.jar:3.8.6.Final]
	at org.xnio.nio.QueuedNioTcpServer2.acceptTask(QueuedNioTcpServer2.java:178) ~[xnio-nio-3.8.6.Final.jar:3.8.6.Final]
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612) [xnio-nio-3.8.6.Final.jar:3.8.6.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479) [xnio-nio-3.8.6.Final.jar:3.8.6.Final]
Caused by: java.lang.NumberFormatException: For input string: "None"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
	at com.google.gson.stream.JsonReader.nextLong(JsonReader.java:964) ~[gson-2.9.0.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:318) ~[gson-2.9.0.jar:?]
      
	... 23 more

This is running on raspberry pi 4 running Debian 11

**Comment by caseyscarborough** [comment]
This seems to be a regression in the API. The `proxy_type` JSON field is now returning the string `"None"` in 4.6.0 when no proxy is set. According to the [API docs](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-application-preferences), this field should only be an integer with the following values:

<img width="531" alt="Screenshot 2023-10-23 at 1 26 05 PM" src="https://github.com/caseyscarborough/qbittorrent-exporter/assets/3237612/ca607d6b-fa7d-4a8e-b701-369aeacdf008">

I added a workaround for this and you can either repull the `latest` tag or use the `v1.3.3` tag and it should be resolved now.

**Comment by robergej** [comment]
Hi, thanks for the super fast reply!!
Unfortunately both 1.3.3 and 1.3.4 don't seem to work for me. Now the exporter won't do anything at all, the log just shows this over and over:

exec /opt/qbittorrent-exporter/bin/qbittorrent-exporter: exec format error
exec /opt/qbittorrent-exporter/bin/qbittorrent-exporter: exec format error
exec /opt/qbittorrent-exporter/bin/qbittorrent-exporter: exec format error
exec /opt/qbittorrent-exporter/bin/qbittorrent-exporter: exec format error
exec /opt/qbittorrent-exporter/bin/qbittorrent-exporter: exec format error

**Comment by caseyscarborough** [comment]
Oof, thanks for letting me know. Your raspberry pi has arm processor, correct?

**Comment by robergej** [comment]
Thank you!

**Comment by caseyscarborough** [comment]
@robergej Try the `latest` or `v1.3.5` tags, it should be good now. Let me know if there's still an issue, and sorry about the trouble.

**Comment by robergej** [comment]
Great that does it, back in business! No need to apologize, thank you for your very fast responsiveness!
