### ISSUE TITLE
"An error occurred. For input string: "0,26""

### ISSUE THREAD

**Issue by MiisterChipsSs** [caseyscarborough/qbittorrent-exporter#22]
Hi,

I'm deploying your exporter on a debian virtual machine. I launch the container on docker and on my logs I see that

> 14:10:35.723 [DEBUG] qbittorrent.exporter.Application - Environment variable QBITTORRENT_USERNAME found with value 'admin'.
14:10:35.724 [DEBUG] qbittorrent.exporter.Application - Environment variable QBITTORRENT_PASSWORD found with value '**password**'.
14:10:35.725 [DEBUG] qbittorrent.exporter.Application - Environment variable QBITTORRENT_HOST was not found. Using default value 'localhost'.
14:10:35.725 [DEBUG] qbittorrent.exporter.Application - Environment variable QBITTORRENT_PORT was not found. Using default value '8080'.
14:10:35.725 [DEBUG] qbittorrent.exporter.Application - Environment variable QBITTORRENT_PROTOCOL was not found. Using default value 'http'.
14:10:35.725 [DEBUG] qbittorrent.exporter.Application - Environment variable QBITTORRENT_BASE_URL found with value 'http://192.168.1.240:8080'.
14:10:35.726 [INFO] qbittorrent.api.ApiClient - Using qBittorrent url http://192.168.1.240:8080
14:10:35.948 [INFO] qbittorrent.exporter.Application - Server is listening for connections at http://0.0.0.0:17871/metrics
14:10:40.614 [INFO] qbittorrent.exporter.handler.QbtHttpHandler - Beginning prometheus metrics collection...
14:10:40.615 [INFO] qbittorrent.api.ApiClient - Authorization cookie has not been set, we need to login first.
14:10:40.615 [INFO] qbittorrent.api.ApiClient - Logging in user admin using http://192.168.1.240:8080/api/v2/auth/login
14:10:40.811 [INFO] qbittorrent.api.ApiClient - Response from /app/version endpoint was 200.
14:10:40.811 [INFO] qbittorrent.api.ApiClient - Successfully logged in with qBittorrent version v4.6.3.
14:10:40.842 [INFO] qbittorrent.api.ApiClient - Response from /torrents/info endpoint was 200.
14:10:40.858 [INFO] qbittorrent.api.ApiClient - Response from /app/preferences endpoint was 200.
14:10:40.862 [WARN] qbittorrent.api.gson.LongTypeAdapter - Could not read long None which had an invalid long value. Defaulting value to 0.
14:10:40.871 [INFO] qbittorrent.api.ApiClient - Response from /sync/maindata endpoint was 200.
14:10:40.876 [INFO] qbittorrent.api.ApiClient - Response from /app/version endpoint was 200.
14:10:40.876 [ERROR] qbittorrent.exporter.handler.QbtHttpHandler - An error occurred calling API
java.lang.NumberFormatException: For input string: "0,26"
	at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054) ~[?:?]
	at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110) ~[?:?]
	at java.lang.Double.parseDouble(Double.java:651) ~[?:?]
	at qbittorrent.exporter.handler.QbtHttpHandler.handleRequest(QbtHttpHandler.java:53) ~[qbittorrent-exporter.jar:?]
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104) ~[undertow-core-2.2.16.Final.jar:2.2.16.Final]
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) ~[undertow-core-2.2.16.Final.jar:2.2.16.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256) ~[undertow-core-2.2.16.Final.jar:2.2.16.Final]
	at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136) ~[undertow-core-2.2.16.Final.jar:2.2.16.Final]
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162) ~[undertow-core-2.2.16.Final.jar:2.2.16.Final]
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100) ~[undertow-core-2.2.16.Final.jar:2.2.16.Final]
	at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57) ~[undertow-core-2.2.16.Final.jar:2.2.16.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.8.6.Final.jar:3.8.6.Final]
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291) ~[xnio-api-3.8.6.Final.jar:3.8.6.Final]
	at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286) ~[xnio-api-3.8.6.Final.jar:3.8.6.Final]
	at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.8.6.Final.jar:3.8.6.Final]
	at org.xnio.nio.QueuedNioTcpServer2.acceptTask(QueuedNioTcpServer2.java:178) ~[xnio-nio-3.8.6.Final.jar:3.8.6.Final]
	at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612) [xnio-nio-3.8.6.Final.jar:3.8.6.Final]
	at org.xnio.nio.WorkerThread.run(WorkerThread.java:479) [xnio-nio-3.8.6.Final.jar:3.8.6.Final]
	
How can I fix that ?

thank you for your help :]

**Comment by vincejv** [comment]
see https://github.com/caseyscarborough/qbittorrent-exporter/issues/15
