### ISSUE TITLE
JSONSyntaxException

### ISSUE THREAD

**Issue by jwynn6** [caseyscarborough/qbittorrent-exporter#6]
Running the docker command  to pull the latest image, customized for my server address and login, has an error occurring when metrics are collected. command and output are below. 

```
root@monitoring:/opt/prometheus# docker run --name=qbittorrent-exporter -e QBITTORRENT_USERNAME=^^^^^ -e QBITTORRENT_PASSWORD=^^^^^^ -e QBITTORRENT_BASE_URL=http://torrent.^^^^^^^^^.com:80  -p 17871:17871 caseyscarborough/qbittorrent-exporter:latest
```

```
/opt/qbittorrent-exporter/bin/qbittorrent-exporter: line 233: xargs: command not found
00:44:05.273 [DEBUG] qbittorrent.exporter.Application - Environment variable QBITTORRENT_USERNAME found with value '^^^^^'.
00:44:05.281 [DEBUG] qbittorrent.exporter.Application - Environment variable QBITTORRENT_PASSWORD found with value '^^^^^'.
00:44:05.281 [DEBUG] qbittorrent.exporter.Application - Environment variable QBITTORRENT_HOST was not found. Using default value 'localhost'.
00:44:05.282 [DEBUG] qbittorrent.exporter.Application - Environment variable QBITTORRENT_PORT was not found. Using default value '8080'.
00:44:05.282 [DEBUG] qbittorrent.exporter.Application - Environment variable QBITTORRENT_PROTOCOL was not found. Using default value 'http'.
00:44:05.282 [DEBUG] qbittorrent.exporter.Application - Environment variable QBITTORRENT_BASE_URL found with value 'http://torrent.^^^^^^^^^.com:80'.
00:44:06.296 [INFO] qbittorrent.exporter.Application - Your qBittorrent version is v4.4.0.
00:44:06.526 [INFO] qbittorrent.exporter.Application - Server is listening for connections at http://0.0.0.0:17871/metrics
00:44:18.964 [INFO] qbittorrent.exporter.handler.QbtHttpHandler - Beginning prometheus metrics collection...
00:44:26.557 [ERROR] qbittorrent.exporter.handler.QbtHttpHandler - An error occurred calling API
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 3162213725 at line 1 column 770 path $.server_state.total_wasted_session
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:231) ~[gson-2.8.8.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:221) ~[gson-2.8.8.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) ~[gson-2.8.8.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) ~[gson-2.8.8.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) ~[gson-2.8.8.jar:?]
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) ~[gson-2.8.8.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.8.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.8.jar:?]
        at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.8.jar:?]
        at qbittorrent.api.ApiClient.getRequest(ApiClient.java:142) ~[qbittorrent-exporter.jar:?]
        at qbittorrent.api.ApiClient.getMainData(ApiClient.java:90) ~[qbittorrent-exporter.jar:?]
        at qbittorrent.exporter.handler.QbtHttpHandler.handleRequest(QbtHttpHandler.java:42) ~[qbittorrent-exporter.jar:?]
        at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:104) ~[undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:387) ~[undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.server.protocol.http.HttpReadListener.handleEventWithNoRunningRequest(HttpReadListener.java:256) ~[undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.server.protocol.http.HttpReadListener.handleEvent(HttpReadListener.java:136) ~[undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:162) ~[undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:100) ~[undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at io.undertow.server.protocol.http.HttpOpenListener.handleEvent(HttpOpenListener.java:57) ~[undertow-core-2.2.12.Final.jar:2.2.12.Final]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.8.4.Final.jar:3.8.4.Final]
        at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:291) ~[xnio-api-3.8.4.Final.jar:3.8.4.Final]
        at org.xnio.ChannelListeners$10.handleEvent(ChannelListeners.java:286) ~[xnio-api-3.8.4.Final.jar:3.8.4.Final]
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92) ~[xnio-api-3.8.4.Final.jar:3.8.4.Final]
        at org.xnio.nio.QueuedNioTcpServer2.acceptTask(QueuedNioTcpServer2.java:178) ~[xnio-nio-3.8.4.Final.jar:3.8.4.Final]
        at org.xnio.nio.WorkerThread.safeRun(WorkerThread.java:612) [xnio-nio-3.8.4.Final.jar:3.8.4.Final]
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:479) [xnio-nio-3.8.4.Final.jar:3.8.4.Final]
Caused by: java.lang.NumberFormatException: Expected an int but was 3162213725 at line 1 column 770 path $.server_state.total_wasted_session
        at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1171) ~[gson-2.8.8.jar:?]
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:229) ~[gson-2.8.8.jar:?]
        ... 25 more
```

**Comment by caseyscarborough** [comment]
Thanks for the report @jwynn6, looks like some values from the API are defined as an `int` but can grow larger than an `int`. I will get this fixed.
